### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by vishaal27** [mlfoundations/clip_quality_not_quantity#2]
Hey, thanks for the great work and releasing code for accessing the exact datasets used for your analysis. I noticed that there was an earlier closed issue that asked about releasing the pre-trained models used, are there any further updates on the models release?
Further, since your work uses CLIP-RN50 models for all your releases, I was wondering if you are aware of any other work that does an analysis with vision-transformers for different data distributions at the medium data scale (<20M), specifically on the CC12M dataset/YFCC15M dataset? I am aware of the Datacomp medium-scale models (12.8M samples) but however I am mainly interested in accessing pre-trained models on the CC12M/YFCC15M dataset. 
Looking forward to hearing your thoughts, thanks!

**Comment by thaonguyen19** [comment]
Hi, thanks for the reminder! I moved on to a different project and forgot to open-source the models..... Will sort out all the checkpoints and upload them onto HuggingFace soon. 

Regarding other CLIP models trained on YFCC15M or CC12M, I only know of this paper (https://proceedings.mlr.press/v162/fang22a) that seems to train a model with ViTB/16 backbone on YFCC15M. You could reach out to the authors for more details. Otherwise perhaps look through the citations of CC12M paper?

**Comment by vishaal27** [comment]
Great thanks for the update, this would be super helpful!

**Comment by vishaal27** [comment]
Hi @thaonguyen19, sorry to bother you again---just checking to see if there is any update on this?

**Comment by vishaal27** [comment]
The models are available here thanks to Thao: https://huggingface.co/thaottn
